- hosts: edmund2

  vars_files:
    - vars/apt_sources.yml
    - vars/userlist.yml
    - vars/pkgs_base.yml
    - vars/pkgs_dev.yml
    - vars/pkgs_bioinf.yml
    - vars/python_pkgs.yml
    - vars/std_modules.yml

  vars:
    - source_dir: /opt/source
    - soft_dir: /opt/apps
    - modules_dir: /opt/modules

  tasks:
    - include: tasks/updatepkgs.yml
    - include: tasks/installpkgs.yml suite="Base" pkgs="{{packages_base}}"
    - include: tasks/base_setup.yml
    - include: tasks/harden.yml

    - include: tasks/users.yml

    - include: tasks/installpkgs.yml suite="Development" pkgs="{{packages_dev}}"
    - include: tasks/installpkgs.yml suite="Bioinformatics" pkgs="{{packages_bioinf}}"
    - include: tasks/lmod.yml lmod_version=6.5.8

    - include: tasks/python_modules.yml modules="{{python_pkgs}}"

    - include: software_modules/htslib.yml tags=htslib version=1.3.1
    - include: software_modules/bcftools.yml tags=bcftools version=1.3.1
    - include: software_modules/samtools.yml tags=samtools version=1.3.1
    - include: software_modules/bwa.yml tags=bwa version=0.7.15
    - include: software_modules/bowtie2.yml tags=bowtie2 version=2.2.9
    - include: software_modules/bowtie.yml tags=bowtie version=1.1.2
    - include: software_modules/vcftools.yml tags=vcftools version=master
