- hosts: all

  vars_files:
    - vars/userlist.yml
    - vars/pkgs_base.yml
    - vars/pkgs_dev.yml
    - vars/pkgs_bioinf.yml

  vars:
    - source_dir: /opt/source
    - soft_dir: /opt/apps
    - modules_dir: /opt/modules

  pre_tasks:
    - include: tasks/updatepkgs.yml
    - include: tasks/installpkgs.yml suite="Base" pkgs="{{packages_base}}"
    - include: tasks/users.yml
    - include: tasks/installpkgs.yml suite="Development" pkgs="{{ packages_dev }}"
    - include: tasks/installpkgs.yml suite="Bioinformatics" pkgs="{{ packages_bioinf }}"
    - include: tasks/lmod.yml lmod_version=6.5.8

  tasks:
    - include: software_modules/bamstats.yml tags=bamstats version=1.25
    - include: software_modules/bamutil.yml tags=bamutil version=1.0.13
    - include: software_modules/bcftools.yml tags=bcftools version=1.3.1
    - include: software_modules/bedops.yml tags=bedops version=2.4.11
    - include: software_modules/blat.yml tags=blat version=35
    - include: software_modules/bowtie.yml tags=bowtie1 version=1.1.1
    - include: software_modules/bowtie2.yml tags=bowtie2 version=2.2.5
    - include: software_modules/bwa.yml tags=bwa version=0.7.15
    - include: software_modules/cufflinks.yml tags=cufflinks version=2.2.1
    - include: software_modules/htslib.yml tags=htslib version=1.3.1
    - include: software_modules/ncbi-blast.yml tags=ncbi-blast version=2.3.0
    - include: software_modules/samtools.yml tags=samtools version=1.3.1 htslib_version=1.3.1
    - include: software_modules/tophat.yml tags=tophat version=2.0.13
    - include: software_modules/trimmomatic.yml tags=trimmomatic version=0.33
    - include: software_modules/trinity.yml tags=trinity version=2.0.6
    - include: software_modules/vcftools.yml tags=vcftools version=0.1.12b
    - include: software_modules/velvet.yml tags=velvet version=1.2.10
