- hosts: edmund.anu.edu.au

  vars_files:
    - vars/apt_sources.yml
    - vars/userlist.yml
    - vars/pkgs_base.yml
    - vars/pkgs_dev.yml
    - vars/pkgs_bioinf.yml
    - vars/python_pkgs.yml
    - vars/std_modules.yml

  vars:
    - source_dir: /opt/source
    - soft_dir: /opt/apps
    - modules_dir: /opt/modules

  tasks:
    - include: tasks/updatepkgs.yml
      tags: base
    - include: tasks/installpkgs.yml suite="Base" pkgs="{{packages_base}}"
      tags: base
    - include: tasks/base_setup.yml
      tags: base
    - include: tasks/harden.yml
      tags: base
    - include: tasks/users.yml
      tags: base

    - include: tasks/installpkgs.yml suite="Development" pkgs="{{packages_dev}}" tags=apt
      tags: pkgs
    - include: tasks/installpkgs.yml suite="Bioinformatics" pkgs="{{packages_bioinf}}" tags=apt
      tags: pkgs
    - include: tasks/python_modules.yml modules="{{python_pkgs}}"
      tags: pkgs

    - include: tasks/lmod.yml lmod_version=6.5.8
      tags: modules
    - include: software_modules/htslib.yml version=1.3.1
      tags: modules,htslib
    - include: software_modules/bcftools.yml version=1.3.1
      tags: modules,bcftools
    - include: software_modules/samtools.yml version=1.3.1
      tags: modules,samtools
    - include: software_modules/bwa.yml version=0.7.15
      tags: modules,bwa
    - include: software_modules/bowtie2.yml version=2.2.9
      tags: modules,bowtie2
    - include: software_modules/bowtie.yml version=1.1.2
      tags: modules,bowtie
    - include: software_modules/vcftools.yml version=master
      tags: modules,vcftools
    - include: software_modules/bedtools.yml version=2.26.0
      tags: modules,bedtools
    - include: software_modules/opencv3.yml version=3.1.0
      tags: modules,opencv3
