- hosts: traitcapture-vm

  vars_files:
    - vars_common/pkgs_base.yml
    - vars_traitcapture/apt_sources.yml
    - vars_traitcapture/userlist.yml
    - vars_traitcapture/pkgs_dev.yml
    - vars_traitcapture/pkgs_traitcapture.yml
    - vars_traitcapture/python_pkgs.yml
    - vars_traitcapture/default-mods.yml


  tasks:
    - include: tasks/updatepkgs.yml
      tags: base
    - include: tasks/installpkgs.yml suite="Base" pkgs="{{packages_base}}"
      tags: base
    - include: tasks/base_setup.yml
      tags: base
    - include: tasks/harden.yml
      tags: base
    - include: tasks/users.yml
      tags: base,users

    - include: tasks/installpkgs.yml suite="Development" pkgs="{{packages_dev}}"
      tags: pkgs
    - include: tasks/installpkgs.yml suite="Traitcapture" pkgs="{{packages_traitcapture}}"
      tags: pkgs
    - include: tasks/python_modules.yml modules="{{python_pkgs}}"
      tags: pkgs

    - include: tasks/lmod.yml lmod_version=6.5.8
      tags: modules

    - include: software_modules/opencv3.yml version=master
      tags: modules,opencv3
