- name: Set mail server name
  lineinfile:
    line: "myhostname = {{ansible_fqdn}}"
    regexp: "^myhostname"
    state: present
    dest: /etc/postfix/main.cf

- name: Disable root logins
  file:
    dest: /root/.ssh/authorized_keys
    state: absent
