- name: "Install Jupyterhub"
  pip:
    name: jupyterhub
    executable: pip3
    state: latest

  #- name: "Install JH npm deps"
  #  npm:
  #    name: configurable-http-proxy
  #    global: true
  #    state: latest

- name: "Install Jupyterhub config"
  template:
    src: templates/jupyterhub_cfg.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
    owner: root
    group: root
    mode: 0644
  with_items: "{{jupyterhub}}"

- name: "Install Jupyterhub systemd"
  template:
    src: templates/jupyterhub_systemd.unit.j2
    dest: /lib/systemd/system/jupyterhub.service
    owner: root
    group: root
    mode: 0644
  with_items: "{{jupyterhub}}"

- name: "Install Jupyterhub apache config"
  template:
    src: templates/jupyterhub_apache.conf.j2
    dest: /etc/jupyterhub/apache.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{jupyterhub}}"

- name: "Enable userdir module"
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - proxy_wstunnel
    - proxy_http
    - headers

- name: "Ensure jupyterhub var dir exists"
  file:
    path: /var/lib/jupyterhub
    state: directory

- name: "Ensure jupyterhub is started"
  service:
    name: jupyterhub
    state: restarted
    enabled: yes

