- name: Add apt sources
  apt_repository: repo={{item}} state=present
  with_items: "{{apt_sources}}"

- name: Add apt keys
  apt_key:
    url: "{{item.url|default(omit)}}"
    id: "{{item.id|default(omit)}}"
    keyserver: "{{item.keyserver|default(omit)}}"
  with_items: "{{apt_keys}}"

- name: Set up apt updates
  lineinfile:
    line: "{{item}}"
    state: present
    insertafter: EOF
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  with_items:
    - 'Unattended-Upgrade::Origins-Pattern {"origin=*";};'

- name: Upgrade pkgs
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
