- name: Make users
  user:
    name: "{{item.name}}"
    state: present
    generate_ssh_key: yes
    groups: "{{','.join(item.groups)}}"
  with_items:
    - "{{users}}"

- name: Add ssh public key
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{lookup('file', 'keys/' + item.1)}}"
  register: keyfiles
  with_subelements:
    - "{{users}}"
    - keys
    - {skip_missing: True}
